# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='comparators',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='condition name'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='disease name'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=study.models.TherapeuticArea),
        ),
        migrations.AlterField(
            model_name='inclusioncriteria',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='investigationproducts',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigationproducts',
            name='doze',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigationproducts',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investigationproducts',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sponsor name'),
        ),
        migrations.AlterField(
            model_name='studyrelatedmaterials',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='therapeuticarea',
            name='name',
            field=models.CharField(blank=True, choices=[('Choose condition', 'Choose condition'), ('Andrology', 'Andrology'), ('Asthma & Allergy', 'Asthma & Allergy'), ('Cardiology & Vascular Diseases', 'Cardiology & Vascular Diseases'), ('Dermatology', 'Dermatology'), ('Dentistry', 'Dentistry'), ('Endocrinology', 'Endocrinology'), ('Gastroentorology', 'Gastroentorology'), ('Gerontology & Geriatrics', 'Gerontology & Geriatrics'), ('Healthy Volunteers', 'Healthy Volunteers'), ('Hematology', 'Hematology'), ('Hepatoogy', 'Hepatoogy'), ('Immunology', 'Immunology'), ('Infectious Diseases', 'Infectious Diseases'), ('Medical Device', 'Medical Device'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Obstetrics & Gynaecology (OB&GYN)', 'Obstetrics & Gynaecology (OB&GYN)'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Otorhinolaryngology', 'Otorhinolaryngology'), ('Pediatrics', 'Pediatrics'), ('Plastic Surgery', 'Plastic Surgery'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Reproductive Medicine', 'Reproductive Medicine'), ('Rheumatology', 'Rheumatology'), ('Surgery', 'Surgery'), ('Traumatology', 'Traumatology'), ('Urology', 'Urology'), ('Venerology', 'Venerology')], default='CHOOSE_CONDITION', max_length=100, null=True, verbose_name='decease name'),
        ),
    ]
