# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20160508_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyidentifiers',
            name='study_status',
            field=models.CharField(choices=[('Not recruiting yet', 'Not recruiting yet'), ('Recruiting', 'Recruiting'), ('On invitation recruiting', 'Invitation needed'), ('Not recruiting', 'Not recruiting'), ('Study end', 'Study finished'), ('Study pause', 'Study paused'), ('Study terminated before recruiting', 'Study ended before recruiting'), ('Study status unknown', 'Unknown study status'), ('Not healthy recruits', 'Recruits with decease only')], default=None, max_length=50, null=True, verbose_name='study status'),
        ),
    ]
