# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20160515_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalStudySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, choices=[('Autonomous Republic of Crimea', 'Autonomous Republic of Crimea'), ('Cherkaska', 'Cherkaska'), ('Chernihivska', 'Chernihivska'), ('Chernivetska', 'Chernivetska'), ('Dnipropetrovska', 'Dnipropetrovska'), ('Donetska', 'Donetska'), ('Ivano-Frankivska', 'Ivano-Frankivska'), ('Kharkivska', 'Kharkivska'), ('Khersonska', 'Khersonska'), ('Khmelnytska', 'Khmelnytska'), ('Kirovohradska', 'Kirovohradska'), ('Kyiv', 'Kyiv'), ('Kyivska', 'Kyivska'), ('Luhanska', 'Luhanska'), ('Lvivska', 'Lvivska'), ('Mykolayivska', 'Mykolayivska'), ('Odeska', 'Odeska'), ('Poltavska', 'Poltavska'), ('Rivnenska', 'Rivnenska'), ('Sumska', 'Sumska'), ('Ternopilska', 'Ternopilska'), ('Vinnytska', 'Vinnytska'), ('Volynska', 'Volynska'), ('Zakarpatska', 'Zakarpatska'), ('Zaporizka', 'Zaporizka'), ('Zhytomyrska', 'Zhytomyrska')], max_length=20, null=True, verbose_name='region')),
                ('principal_investigator_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='principal investigator phone number')),
                ('medical_institution', models.TextField(blank=True, max_length=200, null=True, verbose_name='medical institution')),
                ('medical_institution_department', models.TextField(blank=True, max_length=200, null=True, verbose_name='medical institution department')),
                ('site', models.CharField(blank=True, max_length=100, null=True, verbose_name='web site')),
                ('medical_institution_department_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='medical institution department phone number')),
                ('medical_institution_department_fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='medical institution department fax')),
                ('medical_educational_institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='medical educational institution')),
                ('medical_educational_institution_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='medical educational institution department')),
                ('medical_institution_contact_person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='medical institution contact person name')),
                ('company_contact_person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='company contact person name')),
                ('contact_person_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact person phone number')),
                ('contact_person_fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact person fax')),
                ('contact_person_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='contact person email')),
                ('recruiting_status_clinicaltrials', models.CharField(blank=True, choices=[('Not recruiting yet', 'Not recruiting yet'), ('Recruiting', 'Recruiting'), ('Not recruiting', 'Not recruiting')], max_length=20, null=True, verbose_name='recruiting status clinicaltrials')),
                ('recruiting_status_moh', models.CharField(blank=True, choices=[('Not recruiting yet', 'Not recruiting yet'), ('Recruiting', 'Recruiting'), ('Not recruiting', 'Not recruiting')], default=None, max_length=20, null=True, verbose_name='recruiting status MOH of Ukraine')),
                ('recruiting_status_company', models.CharField(blank=True, choices=[('Not recruiting yet', 'Not recruiting yet'), ('Recruiting', 'Recruiting'), ('Not recruiting', 'Not recruiting')], default=None, max_length=20, null=True, verbose_name='recruiting status company')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.PlaceAddress', verbose_name='address')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.City', verbose_name='city')),
                ('head_of_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.HeadOfDepartment', verbose_name='head of department')),
                ('phone_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.MedicalInstitutionPhoneNumber', verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='AllStudyRelatedMaterials',
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='place',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='place',
            name='principal_investigator',
        ),
        migrations.AlterModelOptions(
            name='allstudyrelatedmaterials',
            options={'ordering': ('name',), 'verbose_name': 'all study-related materials', 'verbose_name_plural': 'all study-related materials'},
        ),
        migrations.RemoveField(
            model_name='eligibility',
            name='age',
        ),
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='email of contact person provided by Sponsor'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='fax',
            field=models.IntegerField(blank=True, null=True, verbose_name='fax of contact person provided by Sponsor'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='telephone number of contact person provided by Sponsor'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='age_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age from'),
        ),
        migrations.AddField(
            model_name='eligibility',
            name='age_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='age to'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='company_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Company', verbose_name='Company that controls conducting of clinical study in Ukraine'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='full name of contact person provided by Sponsor'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='exclusion_criteria',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='exclusion criteria'),
        ),
        migrations.AlterField(
            model_name='eligibility',
            name='inclusion_criteria',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='inclusion criteria'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='name',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.TherapeuticArea'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='phase',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('I/II', 'I/II'), ('I/III', 'I/III'), ('II', 'II'), ('II/III', 'II/III'), ('III', 'III'), ('III/IV', 'III/IV'), ('IV', 'IV')], max_length=20, null=True, verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='protocol_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='protocol title'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='purpose',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='study_design',
            field=models.CharField(blank=True, choices=[('Allocation', 'Allocation'), ('Endpoint Classification', 'Endpoint Classification'), ('Intervention Model', 'Intervention model'), ('Masking', 'Masking'), ('Primary Purpose', 'Primary purpose')], max_length=50, null=True, verbose_name='study design'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='study_type',
            field=models.CharField(blank=True, choices=[('Interventional', 'Interventional'), ('Non-Interventional', 'Non-Interventional')], max_length=50, null=True, verbose_name='study type'),
        ),
        migrations.AlterField(
            model_name='principalinvestigator',
            name='position',
            field=models.CharField(blank=True, choices=[('Head of department', 'Head of department'), ('Candidate of Medical Sciences', 'Candidate of Medical Sciences'), ('Candidate of Biological Sciences', 'Candidate of Biological Sciences'), ('Candidate of Philosophical Sciences', 'Candidate of Philosophical Sciences'), ('Doctor of Medicine (M.D.)', 'Doctor of Medicine (M.D.)'), ('Doctor of Biological Sciences', 'Doctor of Biological Sciences'), ('Doctor of Philosophy (PhD)', 'Doctor of Philosophy (PhD)'), ('Professor', 'Professor'), ('Academician', 'Academician'), ('PhD (Doctor of Pharmacy)', 'PhD (Doctor of Pharmacy)')], max_length=100, null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='sponsor_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Sponsor', verbose_name='sponsor, country'),
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AddField(
            model_name='clinicalstudysite',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.PrincipalInvestigator', verbose_name='principal investigator'),
        ),
    ]
