# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='medical condition')),
                ('name_ukr', models.CharField(blank=True, max_length=100, null=True, verbose_name='medical condition ukrainian')),
                ('therapeutic_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.TherapeuticArea', verbose_name='therapeutic area')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'disease',
                'verbose_name_plural': 'diseases',
            },
        ),
        migrations.RemoveField(
            model_name='disease',
            name='therapeutic_area',
        ),
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'ordering': ('therapeutic_area',), 'verbose_name': 'general information', 'verbose_name_plural': 'general information'},
        ),
        migrations.RenameField(
            model_name='studyidentifiers',
            old_name='eudract',
            new_name='eudract_eng',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='decease_name',
        ),
        migrations.RemoveField(
            model_name='generalinformation',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='address_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address ukrainian'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sponsor name ukrainian'),
        ),
        migrations.AddField(
            model_name='condition',
            name='description_ukr',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='description ukrainian'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='therapeutic_area',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.TherapeuticArea', verbose_name='therapeutic area'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='address_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='address ukrainian'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='name_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sponsor name ukrainian'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='eudract_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EudraCT number ukrainian'),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='medical_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.MedicalCondition', verbose_name='medical condition'),
        ),
    ]
