# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20160615_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationalProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(blank=True, null=True, verbose_name='form')),
                ('doze', models.TextField(blank=True, null=True, verbose_name='doze')),
                ('manufacturer', models.TextField(blank=True, null=True, verbose_name='manufacturer')),
                ('manufacturer_ukr', models.TextField(blank=True, null=True, verbose_name='manufacturer ukrainian')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('country_ukr', models.CharField(blank=True, max_length=100, null=True, verbose_name='country ukrainian')),
            ],
            options={
                'verbose_name': 'investigation product',
                'verbose_name_plural': 'investigation products',
            },
        ),
        migrations.RemoveField(
            model_name='allstudyrelatedmaterials',
            name='comparators',
        ),
        migrations.RemoveField(
            model_name='allstudyrelatedmaterials',
            name='investigation_products',
        ),
        migrations.RemoveField(
            model_name='allstudyrelatedmaterials',
            name='study_related_materials',
        ),
        migrations.RenameField(
            model_name='studyidentifiers',
            old_name='estimated_enrollment_company',
            new_name='estimated_enrollment_company_in_ukraine',
        ),
        migrations.RenameField(
            model_name='studyidentifiers',
            old_name='eudract_eng',
            new_name='eudract',
        ),
        migrations.AddField(
            model_name='comparators',
            name='country_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country ukrainian'),
        ),
        migrations.AddField(
            model_name='comparators',
            name='manufacturer_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='manufacturer ukrainian'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='clinical_study',
            field=models.CharField(blank=True, choices=[('randomized', 'randomized'), ('controlled', 'controlled'), ('opened', 'opened'), ('simple blind', 'simple blind'), ('double blind', 'double blind'), ('with parallel groups', 'with parallel groups'), ('crossed', 'crossed'), ('comparative', 'comparative')], max_length=50, null=True, verbose_name='clinical study'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='clinical_study_conducted',
            field=models.CharField(blank=True, choices=[('only in ukraine', 'only in ukraine'), ('in countries (International)', 'in countries (International)')], max_length=50, null=True, verbose_name='clinical study is conducted'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='clinical_study_conduction_countries',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Countries in which clinical study is conducted'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='detail_description_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='detailed description ukrainian'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='protocol_title_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='protocol title ukrainian'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='purpose_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='purpose ukrainian'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='trial_sites_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantity of trial sites'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='comparators',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.Comparators', verbose_name='comparators'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='estimated_enrollment_moh_in_ukraine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated enrollment in Ukraine according to MOH of Ukraine'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='estimated_last_day_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated study completion date'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='final_enrollment_ukraine_according_company',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final Enrollment in Ukraine according to company'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='final_enrollment_ukraine_according_moh_ukraine',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final Enrollment in Ukraine according to MoH of\xa0Ukraine'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='moh_of_ukraine_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MOH of Ukraine ukrainian'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='start_date_of_enrolling_in_ukraine',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date of enrolling patients in Ukraine'),
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='study_related_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.StudyRelatedMaterials', verbose_name='study related materials'),
        ),
        migrations.AddField(
            model_name='studyrelatedmaterials',
            name='country_ukr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country ukrainian'),
        ),
        migrations.AddField(
            model_name='studyrelatedmaterials',
            name='manufacturer_ukr',
            field=models.TextField(blank=True, null=True, verbose_name='manufacturer ukrainian'),
        ),
        migrations.AddField(
            model_name='studyrelatedmaterials',
            name='name_ukrainian',
            field=models.TextField(blank=True, null=True, verbose_name='name ukrainian'),
        ),
        migrations.AlterField(
            model_name='comparators',
            name='doze',
            field=models.TextField(blank=True, null=True, verbose_name='doze'),
        ),
        migrations.AlterField(
            model_name='comparators',
            name='form',
            field=models.TextField(blank=True, null=True, verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='comparators',
            name='manufacturer',
            field=models.TextField(blank=True, null=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='phase',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('I/II', 'I/II'), ('I/III', 'I/III'), ('II', 'II'), ('II/III', 'II/III'), ('III', 'III'), ('IV', 'IV'), ('pre-registration', 'pre-registration')], max_length=50, null=True, verbose_name='phase'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='protocol_title',
            field=models.TextField(blank=True, null=True, verbose_name='protocol title'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='estimated_enrollment_clinicaltrials_overall',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estimated enrollment in general according to clinicaltrials.gov'),
        ),
        migrations.AlterField(
            model_name='studyidentifiers',
            name='study_status',
            field=models.CharField(choices=[('This study is not yet open for participant recruitment', 'Not recruiting yet'), ('This study is currently recruiting participants', 'Recruiting'), ('This study is enrolling participants by invitation only', 'Invitation needed'), ('This study is ongoing, but not recruiting participants', 'Not recruiting'), ('This study has been completed', 'Study finished'), ('This study has been terminated', 'Study paused'), ('This study has been withdrawn prior to enrollment', 'Study ended before recruiting'), ('The recruitment status of this study is unknown because the information has not been verified recently', 'Unknown study status'), ('This study is not recruiting participants', 'Recruits with decease only')], default=None, max_length=250, null=True, verbose_name='study status'),
        ),
        migrations.AlterField(
            model_name='studyrelatedmaterials',
            name='manufacturer',
            field=models.TextField(blank=True, null=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='studyrelatedmaterials',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='therapeuticarea',
            name='name',
            field=models.CharField(blank=True, choices=[('Therapeutic area', 'Therapeutic area'), ('Andrology', 'Andrology'), ('Asthma & Allergy', 'Asthma & Allergy'), ('Cardiology & Vascular Diseases', 'Cardiology & Vascular Diseases'), ('Dermatology', 'Dermatology'), ('Dentistry', 'Dentistry'), ('Endocrinology', 'Endocrinology'), ('Gastroentorology', 'Gastroentorology'), ('Gerontology & Geriatrics', 'Gerontology & Geriatrics'), ('Healthy Volunteers', 'Healthy Volunteers'), ('Hematology', 'Hematology'), ('Hepatoogy', 'Hepatoogy'), ('Immunology', 'Immunology'), ('Infectious Diseases', 'Infectious Diseases'), ('Medical Device', 'Medical Device'), ('Neurology', 'Neurology'), ('Nephrology', 'Nephrology'), ('Obstetrics & Gynaecology (OB&GYN)', 'Obstetrics & Gynaecology (OB&GYN)'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Otorhinolaryngology', 'Otorhinolaryngology'), ('Pediatrics', 'Pediatrics'), ('Plastic Surgery', 'Plastic Surgery'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Reproductive Medicine', 'Reproductive Medicine'), ('Rheumatology', 'Rheumatology'), ('Surgery', 'Surgery'), ('Traumatology', 'Traumatology'), ('Urology', 'Urology'), ('Venerology', 'Venerology')], default='TRERAPEUTIC_AREA', max_length=100, null=True, verbose_name='decease name'),
        ),
        migrations.DeleteModel(
            name='AllStudyRelatedMaterials',
        ),
        migrations.DeleteModel(
            name='InvestigationProducts',
        ),
        migrations.AddField(
            model_name='studyidentifiers',
            name='investigation_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='study.InvestigationalProducts', verbose_name='investigational products'),
        ),
    ]
